name: Run Tests

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download S3 resource
      run: aws s3 ls s3://torontoraptors-datasets/pose/tagged_data_set/20231127/20231106GSWDET_1/

    - name: Run tests
      run: ./your-test-script.sh
